#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#The stop variable
stop = 4000000

#The fibinacci 1
fib1 = 1

#The fibinacci 2
fib2 = 2

#The fibinacci 3
fib3 = 0

#Length of the fibanacci string that we are checking.
length = 0

#the fibsum is the sum of the even valued fib numbers
fibsum = 0

while fib2 <= stop:
	#checks if the fib value is even if so then it adds it to our tracker
	if fib2 % 2 == 0:
		fibsum = fibsum + fib2

	#########Deals with the movement of the fib numbers ############
	fib3 = fib2 + fib1
	fib1 = fib2
	fib2 = fib3
print fibsum
